name: memos-build-pipeline

on:
  push:
    branches: [main] # run when someone pushes to main
  pull_request:
    branches: [main] # run on PRs targeting main
  workflow_dispatch: # manually run from the Github UI

permissions:
  id-token: write    # required for OIDC — lets the workflow request a JWT
  contents: read     # needed for actions/checkout to clone the repo

# What the workflow actualy does
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo # Clones your repo onto the VM that runs this workflow
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ROLE_ARN }}:role/memos_github_role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker image
        run: docker build -t ${{ vars.ECR_REPO }}:${{ github.sha }} -f dockerfile ./memos

      - name: Push image to ECR
        run: docker push ${{ vars.ECR_REPO }}:${{ github.sha }}