name: memos-deploy-pipeline

on:
  workflow_dispatch: # manually run from the Github UI

permissions:
  id-token: write    # required for OIDC — lets the workflow request a JWT
  contents: read     # needed for actions/checkout to clone the repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo # Clones your repo onto the VM that runs this workflow
        uses: actions/checkout@v6

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ROLE_ARN }}:role/memos_github_role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v6

      - name: Terraform Init
        working-directory: infra
        run: terraform init
        
      - name: Terraform Format
        working-directory: infra
        run: terraform fmt -check -recursive
        
      - name: Terraform Validate
        working-directory: infra
        run: terraform validate
        
      - name: Terraform Lint
        working-directory: infra
        run: tflint
        
      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Render task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infra/modules/ecs/task-definition.json
          container-name: memos
          image: ${{ vars.ECR_REPO }}:${{ github.sha }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: memos_service
          cluster: memos_cluster
          wait-for-service-stability: true

      - name: Post-Deploy Health check
        run: curl https://${{ vars.APP_DOMAIN }}/healthz