name: memos-destroy-pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v6

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::310829530244:role/memos_github_role
          aws-region: eu-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Destroy
        working-directory: infra
        run: terraform destroy -auto-approve